apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
  labels:
    application: prometheus-node-exporter
    version: v0.18.1
    component: node-exporter
  namespace: kube-system
spec:
  selector:
    matchLabels:
      application: prometheus-node-exporter
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: prometheus-node-exporter
      labels:
        application: prometheus-node-exporter
        version: v0.18.1
        component: node-exporter
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: prometheus-node-exporter
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      containers:
      - image: registry.opensource.zalan.do/teapot/prometheus-node-exporter:v0.18.1
        args:
          - --collector.textfile.directory=/prometheus-exporter-data
          - --collector.processes
          - --path.procfs=/host/proc
          - --path.sysfs=/host/sys
        name: prometheus-node-exporter
        ports:
        - name: prom-node-exp
          containerPort: 9100
          hostPort: 9100
        resources:
          limits:
            cpu: {{.Cluster.ConfigItems.node_exporter_cpu}}
            memory: {{.Cluster.ConfigItems.node_exporter_memory}}
          requests:
            cpu: {{.Cluster.ConfigItems.node_exporter_cpu}}
            memory: {{.Cluster.ConfigItems.node_exporter_memory}}
        securityContext:
          privileged: true
        volumeMounts:
        - name: prometheus-node-exporter-volume
          mountPath: /prometheus-exporter-data
          readOnly: false
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: proc
          mountPath: /host/proc
          readOnly: true
      {{- if index .ConfigItems "enable_conntrack_log" }}
      - image: registry.opensource.zalan.do/teapot/prometheus-node-exporter-txt-exporter:v0.0.4
        name: prometheus-node-exporter-conntrack-exporter
        resources:
          limits:
            cpu: 10m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 100Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: prometheus-node-exporter-volume
          mountPath: /prometheus-exporter-data
          readOnly: false
      {{- end }}
      hostNetwork: true
      hostPID: true
      volumes:
        - name: prometheus-node-exporter-volume
          emptyDir:
            medium: Memory
        - name: sys
          hostPath:
            path: /sys
        - name: proc
          hostPath:
            path: /proc
