{{- if eq .ConfigItems.enable_csi_migration "true" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-node-driver
  namespace: kube-system
spec:
  selector:
    matchLabels:
      application: container-storage-interface
      component: driver
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: container-storage-interface
        component: driver
    spec:
      initContainers:
        - name: cleanup
          image: registry.opensource.zalan.do/stups/alpine:3.10.3-5
          command:
             - /bin/sh
          args:
             - -c
             - rm -rf /registration/ebs.csi.aws.com-reg.sock /csi/csi.sock
          resources:
            requests:
              cpu: 10m
              memory: 30Mi
            limits:
              cpu: 10m
              memory: 30Mi
          volumeMounts:
            - mountPath: /csi
              name: plugin-dir
            - mountPath: /registration
              name: registration-dir
      containers:
        - args:
            - node
            - --endpoint=$(CSI_ENDPOINT)
            - --logtostderr
            - --v=5
          env:
            - name: CSI_ENDPOINT
              value: unix:/csi/csi.sock
          image: registry.opensource.zalan.do/teapot/ebs-csi-driver:v0.5.0-master-2
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          name: ebs-plugin
          ports:
            - containerPort: 9808
              name: healthz
              protocol: TCP
          resources:
            requests:
              cpu: 20m
              memory: 50Mi
            limits:
              cpu: 20m
              memory: 50Mi
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /opt/podruntime/kubelet
              mountPropagation: Bidirectional
              name: kubelet-dir
            - mountPath: /csi
              name: plugin-dir
            - mountPath: /dev
              name: device-dir
        - args:
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
            - --v=5
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /opt/podruntime/kubelet/plugins/ebs.csi.aws.com/csi.sock
          image: registry.opensource.zalan.do/teapot/csi-node-driver-registrar:v1.3.0-master-4

          name: node-driver-registrar
          resources:
            requests:
              cpu: 20m
              memory: 50Mi
            limits:
              cpu: 20m
              memory: 50Mi
          volumeMounts:
            - mountPath: /csi
              name: plugin-dir
            - mountPath: /registration
              name: registration-dir
        - args:
            - --csi-address=/csi/csi.sock
          image: registry.opensource.zalan.do/teapot/livenessprobe:v2.0.0-master-4
          name: liveness-probe
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - mountPath: /csi
              name: plugin-dir
      hostNetwork: true
      priorityClassName: system-node-critical
      serviceAccountName: ebs-csi-node
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute
      volumes:
        - hostPath:
            path: /opt/podruntime/kubelet
            type: Directory
          name: kubelet-dir
        - hostPath:
            path: /opt/podruntime/kubelet/plugins/ebs.csi.aws.com/
            type: DirectoryOrCreate
          name: plugin-dir
        - hostPath:
            path: /opt/podruntime/kubelet/plugins_registry/
            type: Directory
          name: registration-dir
        - hostPath:
            path: /dev
            type: Directory
          name: device-dir
{{- end }}
