apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: ebs-csi-controller
  namespace: kube-system
  labels:
    application: kubernetes
    component: ebs-csi-driver
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ebs-csi-controller
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: csi-provisioner
    {{ range $NodePool := .Cluster.NodePools }}
    {{ if eq $NodePool.Name "default-master" }}
    # Scaling is relative to r6g.large (smallest master node)
    # 0.006 -> ~90Mi memory, 0.031 -> ~55m CPU
    {{ $scaledCPU := scaleQuantity ( instanceTypeCPUQuantity ( index .InstanceTypes 0 )) 0.031 }}
    {{ $scaledMemory := scaleQuantity ( instanceTypeMemoryQuantity ( index .InstanceTypes 0 )) 0.006 }}
      maxAllowed:
        cpu: {{ $scaledCPU }}
        memory: {{ $scaledMemory }}
    - containerName: csi-attacher
      maxAllowed:
        cpu: {{ $scaledCPU }}
        memory: {{ $scaledMemory }}
    - containerName: csi-resizer
      maxAllowed:
        cpu: {{ $scaledCPU }}
        memory: {{ $scaledMemory }}
    {{ end }}
    {{ end }}
