{{ if eq .ConfigItems.enable_ingress_template_controller "true"}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-template-controller
  namespace: kube-system
  labels:
    application: ingress-template-controller
    version: master-5
spec:
  replicas: 1
  selector:
    matchLabels:
      application: ingress-template-controller
  template:
    metadata:
      labels:
        application: ingress-template-controller
        version: master-5
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      priorityClassName: system-cluster-critical
      serviceAccountName: system
      containers:
      - name: ingress-template-controller
        image: pierone.stups.zalan.do/teapot/ingress-template-controller:master-5
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
{{ end }}
