apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-template-controller
  namespace: kube-system
  labels:
    application: ingress-template-controller
    version: master-4
spec:
  selector:
    matchLabels:
      application: ingress-template-controller
  template:
    metadata:
      labels:
        application: ingress-template-controller
        version: master-4
    spec:
      serviceAccountName: system
      containers:
      - name: ingress-template-controller
        image: pierone.stups.zalan.do/teapot/ingress-template-controller:master-4
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
