apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    application: cluster-autoscaler
    version: v0.3-3
spec:
  replicas: 1
  selector:
    matchLabels:
      application: cluster-autoscaler
  template:
    metadata:
      labels:
        application: cluster-autoscaler
        version: v0.3-3
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
        iam.amazonaws.com/role: "{{ .LocalID }}-app-autoscaler"
    spec:
      containers:
        - image: registry.opensource.zalan.do/teapot/kube-aws-autoscaler:0.3-3-g56f0ca4
          name: cluster-autoscaler
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
