apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    application: cluster-autoscaler
    version: v0.9
spec:
  replicas: 1
  selector:
    matchLabels:
      application: cluster-autoscaler
  template:
    metadata:
      labels:
        application: cluster-autoscaler
        version: v0.9
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        iam.amazonaws.com/role: "{{ .LocalID }}-app-autoscaler"
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - name: cluster-autoscaler
        image: registry.opensource.zalan.do/teapot/kube-aws-autoscaler:0.9-1
        envFrom:
        - configMapRef:
            # load buffer settings from ConfigMap e.g. to set spare nodes to zero for test environments
            name: cluster-autoscaler-{{ .Environment }}
            optional: true
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 100Mi
      dnsPolicy: Default
