apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-job-cleaner
  namespace: kube-system
  labels:
    application: kube-job-cleaner
    version: "0.3"
spec:
  schedule: "17 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 120
      template:
        metadata:
          labels:
            application: kube-job-cleaner
            version: "0.3"
        spec:
          serviceAccountName: system
          restartPolicy: Never
          containers:
          - name: cleaner
            # delete all completed jobs after one hour
            image: registry.opensource.zalan.do/teapot/kube-job-cleaner:0.4-1
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 50m
                memory: 50Mi
