apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-lifecycle-controller
  namespace: kube-system
  labels:
    application: kubernetes
    component: cluster-lifecycle-controller
    version: master-23
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: cluster-lifecycle-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: kubernetes
        component: cluster-lifecycle-controller
        deployment: cluster-lifecycle-controller
        version: master-23
      annotations:
        logging/destination: "{{.Cluster.ConfigItems.log_destination_both}}"
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      serviceAccountName: cluster-lifecycle-controller
      tolerations:
      - key: node.kubernetes.io/role
        value: master
        effect: NoSchedule
      - key: node.kubernetes.io/not-ready
        operator: Exists
      containers:
      - name: cluster-lifecycle-controller
        image: registry.opensource.zalan.do/teapot/cluster-lifecycle-controller:master-23
        args:
            - --drain-grace-period={{.Cluster.ConfigItems.drain_grace_period}}
            - --drain-min-pod-lifetime={{.Cluster.ConfigItems.drain_min_pod_lifetime}}
            - --drain-min-healthy-sibling-lifetime={{.Cluster.ConfigItems.drain_min_healthy_sibling_lifetime}}
            - --drain-min-unhealthy-sibling-lifetime={{.Cluster.ConfigItems.drain_min_unhealthy_sibling_lifetime}}
            - --drain-force-evict-interval={{.Cluster.ConfigItems.drain_force_evict_interval}}
        resources:
          limits:
            cpu: 15m
            memory: 250Mi
          requests:
            cpu: 15m
            memory: 250Mi
        env:
        - name: AWS_REGION
          value: {{ .Region }}
      nodeSelector:
        node.kubernetes.io/role: master
