apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: kubernetes
    component: kube-metrics-adapter
  name: kube-metrics-adapter
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: kube-metrics-adapter
  template:
    metadata:
      labels:
        application: kubernetes
        component: kube-metrics-adapter
        deployment: kube-metrics-adapter
      annotations:
        logging/destination: "{{.Cluster.ConfigItems.log_destination_infra}}"
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      serviceAccountName: custom-metrics-apiserver
      containers:
      - name: kube-metrics-adapter
        image: container-registry.zalando.net/teapot/kube-metrics-adapter:v0.2.2-57-g12dca32
        env:
        - name: AWS_REGION
          value: {{ .Cluster.Region }}
        args:
        - --prometheus-server=http://prometheus.kube-system.svc.cluster.local
        - --skipper-ingress-metrics
        - --skipper-routegroup-metrics
        - --external-rps-metrics
        - --scaling-schedule
        - --scaling-schedule-default-scaling-window={{.Cluster.ConfigItems.kube_metrics_adapter_default_scaling_window}}
        - --scaling-schedule-ramp-steps={{.Cluster.ConfigItems.kube_metrics_adapter_scaling_schedule_ramp_steps}}
        - --aws-external-metrics
        - --aws-region={{.Cluster.Region}}
        - --aws-region=eu-west-1
        - --skipper-backends-annotation=zalando.org/backend-weights
        {{ if eq .Cluster.Environment "production" }}
        - --zmon-kariosdb-endpoint={{.Cluster.ConfigItems.zmon_kairosdb_url}}
        {{ end }}
        {{- if ne .Cluster.ConfigItems.nakadi_url "" }}
        - --nakadi-endpoint={{.Cluster.ConfigItems.nakadi_url}}
        {{- end }}
        volumeMounts:
        {{- if or (eq .Cluster.Environment "production") (ne .Cluster.ConfigItems.nakadi_url "") }}
        - name: credentials
          mountPath: /meta/credentials
          readOnly: true
        {{- end }}
        resources:
          limits:
            cpu: 10m
            memory: 4Gi
          requests:
            cpu: 10m
            memory: 4Gi
      volumes:
      {{- if or (eq .Cluster.Environment "production") (ne .Cluster.ConfigItems.nakadi_url "") }}
      - name: credentials
        secret:
          secretName: "kube-metrics-adapter"
      {{- end }}
