apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: kube-metrics-adapter
  name: kube-metrics-adapter
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-metrics-adapter
  template:
    metadata:
      {{ if eq .ConfigItems.kube_aws_iam_controller_kube_system_enable "false"}}
      annotations:
        iam.amazonaws.com/role: {{ .LocalID}}-kube-metrics-adapter
      {{ end }}
      labels:
        application: kube-metrics-adapter
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      priorityClassName: system-cluster-critical
      serviceAccountName: custom-metrics-apiserver
      containers:
      - name: kube-metrics-adapter
        image: registry.opensource.zalan.do/teapot/kube-metrics-adapter:master-31
        {{ if eq .ConfigItems.kube_aws_iam_controller_kube_system_enable "true"}}
        env:
        # must be set for the AWS SDK/AWS CLI to find the credentials file.
        - name: AWS_SHARED_CREDENTIALS_FILE # used by golang SDK
          value: /meta/aws-iam/credentials.process
        {{ end }}
        args:
        - --prometheus-server=http://prometheus.kube-system.svc.cluster.local
        - --skipper-ingress-metrics
        - --aws-external-metrics
        - --aws-region=eu-central-1
        - --aws-region=eu-west-1
        - --skipper-backends-annotation=zalando.org/stack-traffic-weights
        - --skipper-backends-annotation=zalando.org/backend-weights
        {{ if eq .Environment "production" }}
        - --zmon-kariosdb-endpoint=https://data-service.zmon.zalan.do/kairosdb-proxy
        {{ end }}
        volumeMounts:
        {{ if eq .ConfigItems.kube_aws_iam_controller_kube_system_enable "true"}}
        - name: aws-iam-credentials
          mountPath: /meta/aws-iam
          readOnly: true
        {{ end }}
        {{ if eq .Environment "production" }}
        - name: credentials
          mountPath: /meta/credentials
          readOnly: true
        {{ end }}
        resources:
          limits:
            cpu: 10m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 100Mi
      volumes:
      {{ if eq .ConfigItems.kube_aws_iam_controller_kube_system_enable "true"}}
      - name: aws-iam-credentials
        secret:
          secretName: kube-metrics-adapter-aws-iam-credentials
      {{ end }}
      {{ if eq .Environment "production" }}
      - name: credentials
        secret:
          secretName: "kube-metrics-adapter"
      {{ end }}
