{{ $zone := "eu-central-1b" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaling-buffer-{{$zone}}
  namespace: kube-system
  labels:
    application: autoscaling-buffer
    zone: {{$zone}}
spec:
  replicas: {{.ConfigItems.autoscaling_buffer_pods}}
  selector:
    matchLabels:
      application: autoscaling-buffer
      zone: {{$zone}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: autoscaling-buffer
        zone: {{$zone}}
    spec:
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: "{{$zone}}"
      priorityClassName: autoscaling-buffer
      terminationGracePeriodSeconds: 0
      containers:
      - name: pause
        image: registry.opensource.zalan.do/teapot/pause-amd64:3.1
        resources:
{{ with $resources := autoscalingBufferSettings . }}
          limits:
            cpu: {{$resources.CPU}}
            memory: {{$resources.Memory}}
          requests:
            cpu: {{$resources.CPU}}
            memory: {{$resources.Memory}}
{{ end }}
