apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-monitor
  namespace: kube-system
  labels:
    application: node-monitor
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      application: node-monitor
  template:
    metadata:
      labels:
        application: node-monitor
      annotations:
        logging/destination: "{{.Cluster.ConfigItems.log_destination_infra}}"
    spec:
      hostNetwork: true
      hostPID: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      priorityClassName: system-node-critical
      serviceAccountName: node-monitor
      containers:
        - name: cadvisor
          image: registry.opensource.zalan.do/teapot/cadvisor:v0.34.0-master-5
          args:
            - --port=9101
            - --housekeeping_interval=10s
            - --max_housekeeping_interval=15s
            - --event_storage_event_limit=default=0
            - --event_storage_age_limit=default=0
            - --disable_metrics=sched,percpu,tcp,udp
            - --docker_only
            - --raw_cgroup_prefix_whitelist=/system.slice/kubelet.service
            - --store_container_labels=false
            - --whitelisted_container_labels=io.kubernetes.container.name,io.kubernetes.pod.name,io.kubernetes.pod.namespace,io.kubernetes.pod.uid,application
          resources:
            requests:
              cpu: "{{ .ConfigItems.cadvisor_cpu }}"
              memory: "{{ .ConfigItems.cadvisor_memory }}"
              ephemeral-storage: 256Mi
            limits:
              cpu: "{{ .ConfigItems.cadvisor_cpu }}"
              memory: "{{ .ConfigItems.cadvisor_memory }}"
          securityContext:
            privileged: true # allows reading /dev/kmsg
          volumeMounts:
            - name: rootfs
              mountPath: /rootfs
              readOnly: true
            - name: var-run
              mountPath: /var/run
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: docker
              mountPath: /opt/podruntime/docker
              readOnly: true
            - name: kmsg
              mountPath: /dev/kmsg
              readOnly: true
          ports:
            - name: cadvisor
              containerPort: 9101
              hostPort: 9101
              protocol: TCP
        - image: registry.opensource.zalan.do/teapot/prometheus-node-exporter:v1.3.1
          args:
{{- if eq .Cluster.ConfigItems.node_exporter_experimental_metrics "true" }}
            - --collector.ethtool
{{- end }}
            - --collector.processes
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --path.rootfs=/host
            - --collector.filesystem.mount-points-exclude=^/(dev|proc|run|sys|host|var/lib/lxcfs|opt/podruntime/docker/.+|opt/podruntime/kubelet/.+)($|/)
            - --collector.netdev.device-exclude=^veth.*$
            - --collector.netclass.ignored-devices=^veth.*$
          name: prometheus-node-exporter
          ports:
            - name: prom-node-exp
              containerPort: 9100
              hostPort: 9100
              protocol: TCP
          resources:
            requests:
              cpu: {{.Cluster.ConfigItems.node_exporter_cpu}}
              memory: {{.Cluster.ConfigItems.node_exporter_memory}}
              ephemeral-storage: 256Mi
            limits:
              cpu: {{.Cluster.ConfigItems.node_exporter_cpu}}
              memory: {{.Cluster.ConfigItems.node_exporter_memory}}
          securityContext:
            privileged: true
          volumeMounts:
            - name: rootfs
              mountPath: /host
              readOnly: true
{{- if eq .Cluster.ConfigItems.journald_reader_enabled "true" }}
        - image: registry.opensource.zalan.do/teapot/journald-reader:master-6
          name: journald-reader
          env:
            - name: JOURNALD_READER_CHECKPOINT_FILE
              value: /journald-reader-state/cursor
          resources:
            requests:
              cpu: {{.Cluster.ConfigItems.journald_reader_cpu}}
              memory: {{.Cluster.ConfigItems.journald_reader_memory}}
              ephemeral-storage: 256Mi
            limits:
              cpu: {{.Cluster.ConfigItems.journald_reader_cpu}}
              memory: {{.Cluster.ConfigItems.journald_reader_memory}}
          volumeMounts:
            - mountPath: /var/log/journal
              name: journald-logs
              readOnly: true
            - mountPath: /journald-reader-state
              name: journald-reader-state
{{- end }}
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      volumes:
        - name: rootfs
          hostPath:
            path: /
        - name: var-run
          hostPath:
            path: /var/run
        - name: sys
          hostPath:
            path: /sys
        - name: docker
          hostPath:
            path: /opt/podruntime/docker
        - name: kmsg
          hostPath:
            path: /dev/kmsg
{{- if eq .Cluster.ConfigItems.journald_reader_enabled "true" }}
        - name: journald-logs
          hostPath:
            path: /var/log/journal
        - name: journald-reader-state
          hostPath:
            path: /var/run/journald-reader
            type: DirectoryOrCreate
{{- end }}
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute
