apiVersion: apps/v1
kind: Deployment
metadata:
  name: "zmon-aws-agent"
  namespace: "visibility"
  labels:
    application: "zmon-aws-agent"
    version: "v75-zv155"
spec:
  replicas: {{.ConfigItems.zmon_aws_agent_replicas}}
  selector:
    matchLabels:
      application: zmon-aws-agent
  template:
    metadata:
      labels:
        application: "zmon-aws-agent"
        version: "v75-zv155"
      annotations:
        iam.amazonaws.com/role: "{{ .LocalID }}-app-zmon"
    spec:
      priorityClassName: visibility-zmon
      initContainers:
      - name: gerry-init
        image: registry.opensource.zalan.do/teapot/gerry:v0.0.14
        args:
          - /meta/credentials
          - --application-id=gerry
          - --mint-bucket=s3://{{ .ConfigItems.gerry_mint_bucket }}
          - --once
        resources:
          limits:
            cpu: 5m
            memory: 20Mi
          requests:
            cpu: 5m
            memory: 20Mi

        volumeMounts:
          - name: credentials
            mountPath: /meta/credentials
            readOnly: false

      containers:
        - name: zmon-aws-agent
          image: pierone.stups.zalan.do/zmon/zmon-aws-agent:v75-zv155
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: OAUTH2_ACCESS_TOKEN_URL
              value: https://token.services.auth.zalando.com/oauth2/access_token?realm=/services
            - name: CREDENTIALS_DIR
              value: /meta/credentials
            - name: EXTRA_ENTITY_FIELDS
              value: "environment={{ .Environment }}"

          volumeMounts:
            - name: credentials
              mountPath: /meta/credentials
              readOnly: true

        - name: gerry
          image: registry.opensource.zalan.do/teapot/gerry:v0.0.14
          args:
            - /meta/credentials
            - --application-id=gerry
            - --mint-bucket=s3://{{ .ConfigItems.gerry_mint_bucket }}
          resources:
            limits:
              cpu: 5m
              memory: 20Mi
            requests:
              cpu: 5m
              memory: 20Mi

          volumeMounts:
            - name: credentials
              mountPath: /meta/credentials
              readOnly: false

      volumes:
        - name: credentials
          emptyDir:
            medium: Memory
