apiVersion: apps/v1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
  labels:
    application: heapster
    kubernetes.io/cluster-service: "true"
    version: v1.5.4
spec:
  replicas: 1
  selector:
    matchLabels:
      application: heapster
  template:
    metadata:
      labels:
        application: heapster
        version: v1.5.4
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      priorityClassName: system-cluster-critical
      serviceAccountName: heapster
      containers:
        - image: registry.opensource.zalan.do/teapot/heapster:v1.5.4
          name: heapster
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 100m
              memory: 250Mi
            requests:
              cpu: 100m
              memory: 250Mi
          command:
            - /heapster
            - --source=kubernetes.summary_api:''
