{{ if eq .Environment "production" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: admission-controller-proxy
  namespace: kube-system
  labels:
    application: admission-controller-proxy
spec:
  selector:
    matchLabels:
      application: admission-controller-proxy
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: admission-controller-proxy
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      serviceAccountName: admission-controller-proxy
      dnsPolicy: Default
      hostNetwork: true
      tolerations:
      - key: node.kubernetes.io/role
        value: master
        effect: NoSchedule
      containers:
      - name: cluster-autoscaler
        image: registry.opensource.zalan.do/teapot/admission-controller:master-96
        command:
          - /registry-proxy
          - --address=127.0.0.1:8285
          - --token-secret=/meta/credentials/admission-controller-token-secret
          - --token-type=/meta/credentials/admission-controller-token-type
        resources:
          limits:
            cpu: 25m
            memory: 50Mi
          requests:
            cpu: 25m
            memory: 50Mi
        volumeMounts:
          - name: credentials
            mountPath: /meta/credentials
            readOnly: true
      nodeSelector:
        node.kubernetes.io/role: master
      volumes:
        - name: credentials
          secret:
            secretName: "admission-controller-proxy"
{{ end }}
