apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zmon-worker
  namespace: kube-system
spec:
  replicas: 4
  selector:
    matchLabels:
      application: zmon-worker
  template:
    metadata:
      labels:
        application: zmon-worker
        version: "zv225"
      annotations:
        iam.amazonaws.com/role: "{{ .LocalID }}-app-zmon"
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
        - name: zmon-worker
          image: "pierone.stups.zalan.do/stups/zmon-worker:zv225"
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 2Gi

          ports:
            - containerPort: 8080

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60

          env:
            - name: WORKER_ZMON_QUEUES
              value: zmon:queue:default/24
            - name: WORKER_REDIS_SERVERS
              value: zmon-redis:6379
            - name: WORKER_PLUGIN_SCALYR_READ_KEY
              valueFrom:
                secretKeyRef:
                  name: zmon-worker
                  key: scalyr-read-key
            - name: WORKER_ACCOUNT
              value: "{{ .InfrastructureAccount }}"
            - name: WORKER_REGION
              value: "{{ .Region }}"
            - name: WORKER_PLUGIN_SQL_USER
              valueFrom:
                secretKeyRef:
                  name: zmon-worker
                  key: sql-user
            - name: WORKER_PLUGIN_SQL_PASS
              valueFrom:
                secretKeyRef:
                  name: zmon-worker
                  key: sql-pass

            - name: OAUTH2_ACCESS_TOKEN_URL
              value: https://token.services.auth.zalando.com/oauth2/access_token?realm=/services
            - name: CREDENTIALS_DIR
              value: /meta/credentials

          volumeMounts:
            - name: credentials
              mountPath: /meta/credentials
              readOnly: true

        - name: gerry
          image: registry.opensource.zalan.do/teapot/gerry:v0.0.14
          args:
            - /meta/credentials
            - --application-id=gerry
            - --mint-bucket=s3://{{ .ConfigItems.gerry_mint_bucket }}

          volumeMounts:
            - name: credentials
              mountPath: /meta/credentials
              readOnly: false

      volumes:
        - name: credentials
          emptyDir:
            medium: Memory
