apiVersion: apps/v1
kind: Deployment
metadata:
  name: zmon-worker
  namespace: visibility
  labels:
    application: zmon-worker
    version: "v201-zv247"
spec:
  replicas: {{if index .ConfigItems "zmon_worker_replicas"}}{{.ConfigItems.zmon_worker_replicas}}{{else}}4{{end}}
  selector:
    matchLabels:
      application: zmon-worker
  template:
    metadata:
      labels:
        application: zmon-worker
        version: "v201-zv247"
      annotations:
        iam.amazonaws.com/role: "{{ .LocalID }}-app-zmon"
    spec:
      priorityClassName: visibility-zmon
      serviceAccountName: zmon
      initContainers:
      - name: gerry-init
        image: registry.opensource.zalan.do/teapot/gerry:v0.0.14
        args:
        - /meta/credentials
        - --application-id=gerry
        - --mint-bucket=s3://{{ .ConfigItems.gerry_mint_bucket }}
        - --once
        resources:
          limits:
            cpu: 5m
            memory: 20Mi
          requests:
            cpu: 5m
            memory: 20Mi
        volumeMounts:
          - name: credentials
            mountPath: /meta/credentials
            readOnly: false
      containers:
        - name: zmon-worker
          image: "pierone.stups.zalan.do/zmon/zmon-worker:v201-zv247"
          resources:
            limits:
              cpu: {{if index .ConfigItems "zmon_worker_cpu"}}{{.ConfigItems.zmon_worker_cpu}}{{else}}500m{{end}}
              memory: {{if index .ConfigItems "zmon_worker_mem"}}{{.ConfigItems.zmon_worker_mem}}{{else}}2Gi{{end}}
            requests:
              cpu: {{if index .ConfigItems "zmon_worker_cpu"}}{{.ConfigItems.zmon_worker_cpu}}{{else}}500m{{end}}
              memory: {{if index .ConfigItems "zmon_worker_mem"}}{{.ConfigItems.zmon_worker_mem}}{{else}}2Gi{{end}}

          ports:
            - containerPort: 8080

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60

          env:
            - name: WORKER_ZMON_QUEUES
              value: zmon:queue:default/{{if index .ConfigItems "zmon_worker_count"}}{{.ConfigItems.zmon_worker_count}}{{else}}24{{end}}
            - name: WORKER_REDIS_SERVERS
              value: zmon-redis:6379
            - name: WORKER_PLUGIN_SCALYR_READ_KEY
              valueFrom:
                secretKeyRef:
                  name: zmon-worker
                  key: scalyr-read-key
            - name: WORKER_ACCOUNT
              value: "{{ .InfrastructureAccount }}"
            - name: WORKER_REGION
              value: "{{ .Region }}"
            - name: WORKER_TEAM
              value: "{{ .Alias }}"
            - name: WORKER_PLUGIN_SQL_USER
              valueFrom:
                secretKeyRef:
                  name: zmon-worker
                  key: sql-user
            - name: WORKER_PLUGIN_SQL_PASS
              valueFrom:
                secretKeyRef:
                  name: zmon-worker
                  key: sql-pass

            - name: OAUTH2_ACCESS_TOKEN_URL
              value: https://token.services.auth.zalando.com/oauth2/access_token?realm=/services
            - name: CREDENTIALS_DIR
              value: /meta/credentials

          volumeMounts:
            - name: credentials
              mountPath: /meta/credentials
              readOnly: true

        - name: gerry
          image: registry.opensource.zalan.do/teapot/gerry:v0.0.14
          args:
            - /meta/credentials
            - --application-id=gerry
            - --mint-bucket=s3://{{ .ConfigItems.gerry_mint_bucket }}
          resources:
            limits:
              cpu: 5m
              memory: 20Mi
            requests:
              cpu: 5m
              memory: 20Mi

          volumeMounts:
            - name: credentials
              mountPath: /meta/credentials
              readOnly: false

      volumes:
        - name: credentials
          emptyDir:
            medium: Memory
