apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-static-egress-controller
  namespace: kube-system
  labels:
    application: kube-static-egress-controller
    version: v0.1.10
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-static-egress-controller
  template:
    metadata:
      labels:
        application: kube-static-egress-controller
        version: v0.1.10
{{ if eq .ConfigItems.kube_aws_iam_controller_kube_system_enable "false"}}
      annotations:
        iam.amazonaws.com/role: "{{ .LocalID }}-static-egress-controller"
{{ end }}
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      priorityClassName: system-cluster-critical
      containers:
      - name: controller
        image: registry.opensource.zalan.do/teapot/kube-static-egress-controller:v0.1.10
        args:
        - "--provider=aws"
{{- range $subnet := stupsNATSubnets .Values.vpc_ipv4_cidr }}
        - "--aws-nat-cidr-block={{ $subnet }}"
{{- end }}
{{ range $zone := .Values.availability_zones }}
        - "--aws-az={{ $zone }}"
{{ end }}
        - "--stack-termination-protection"
        env:
        - name: AWS_REGION
          value: eu-central-1
{{ if eq .ConfigItems.kube_aws_iam_controller_kube_system_enable "true"}}
        # must be set for the AWS SDK/AWS CLI to find the credentials file.
        - name: AWS_SHARED_CREDENTIALS_FILE # used by golang SDK
          value: /meta/aws-iam/credentials.process
{{ end }}
{{ if eq .ConfigItems.kube_aws_iam_controller_kube_system_enable "true"}}
        volumeMounts:
        - name: aws-iam-credentials
          mountPath: /meta/aws-iam
          readOnly: true
{{ end }}
        resources:
          limits:
            cpu: 5m
            memory: 50Mi
          requests:
            cpu: 5m
            memory: 50Mi
{{ if eq .ConfigItems.kube_aws_iam_controller_kube_system_enable "true"}}
      volumes:
      - name: aws-iam-credentials
        secret:
          secretName: kube-static-egress-controller-aws-iam-credentials
{{ end }}
