apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-static-egress-controller
  namespace: kube-system
  labels:
    application: kube-static-egress-controller
    version: v0.1.3
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-static-egress-controller
  template:
    metadata:
      labels:
        application: kube-static-egress-controller
        version: v0.1.3
      annotations:
        iam.amazonaws.com/role: "{{ .LocalID }}-static-egress-controller"
    spec:
      priorityClassName: system-cluster-critical
      containers:
      - name: controller
        image: registry.opensource.zalan.do/teapot/kube-static-egress-controller:v0.1.3
        args:
        - "--log-level=debug"
        - "--provider=aws"
        - "--aws-nat-cidr-block=172.31.64.0/28"
        - "--aws-nat-cidr-block=172.31.64.16/28"
        - "--aws-nat-cidr-block=172.31.64.32/28"
        - "--aws-az=eu-central-1a"
        - "--aws-az=eu-central-1b"
        - "--aws-az=eu-central-1c"
        - "--stack-termination-protection"
        env:
        - name: AWS_REGION
          value: eu-central-1
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 5m
            memory: 25Mi
