apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-static-egress-controller
  namespace: kube-system
  labels:
    application: kube-static-egress-controller
    version: v0.2.8
spec:
  replicas: {{if eq .Cluster.ConfigItems.static_egress_controller_enabled "true"}}1{{else}}0{{end}}
  selector:
    matchLabels:
      application: kube-static-egress-controller
  template:
    metadata:
      labels:
        application: kube-static-egress-controller
        version: v0.2.8
      annotations:
        logging/destination: "{{.Cluster.ConfigItems.log_destination_both}}"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      serviceAccountName: kube-static-egress-controller
      containers:
      - name: controller
        image: registry.opensource.zalan.do/teapot/kube-static-egress-controller:v0.2.8-r1
        args:
        - "--provider=aws"
        - "--vpc-id={{.Cluster.ConfigItems.vpc_id}}"
{{- range $subnet := stupsNATSubnets .Values.vpc_ipv4_cidr }}
        - "--aws-nat-cidr-block={{ $subnet }}"
{{- end }}
{{ range $zone := .Values.availability_zones }}
        - "--aws-az={{ $zone }}"
{{ end }}
        - "--stack-termination-protection"
        - "--cluster-id={{ .ID }}"
        - "--additional-stack-tags=InfrastructureComponent=true"
        env:
        - name: AWS_REGION
          value: eu-central-1
        resources:
          limits:
            cpu: 5m
            memory: 50Mi
          requests:
            cpu: 5m
            memory: 50Mi
        ports:
          - containerPort: 8000
            protocol: TCP
