apiVersion: apps/v1
kind: Deployment
metadata:
  name: "zmon-agent"
  namespace: "kube-system"
  labels:
    application: "zmon-agent"
    version: "0.1-a50-zv1"
spec:
  replicas: 1
  selector:
    matchLabels:
      application: zmon-agent
  template:
    metadata:
      labels:
        application: "zmon-agent"
        version: "0.1-a50-zv1"
      annotations:
        iam.amazonaws.com/role: "{{ .LocalID }}-app-zmon"
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists

      initContainers:
      - name: gerry-init
        image: registry.opensource.zalan.do/teapot/gerry:v0.0.14
        args:
          - /meta/credentials
          - --application-id=gerry
          - --mint-bucket=s3://{{ .ConfigItems.gerry_mint_bucket }}
          - --once
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi

        volumeMounts:
          - name: credentials
            mountPath: /meta/credentials
            readOnly: false

      containers:
        - name: zmon-agent
          image: "pierone.stups.zalan.do/zmon/zmon-agent-core:0.1-a50-zv1"
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 80Mi

          env:
            - name: ZMON_AGENT_INFRASTRUCTURE_ACCOUNT
              value: "{{ .InfrastructureAccount }}"
            - name: ZMON_AGENT_REGION
              value: "{{ .Region }}"
            - name: ZMON_AGENT_INTERVAL
              value: "60"

            - name: ZMON_AGENT_ENTITY_SERVICE_URL
              value: https://data-service.zmon.zalan.do

            - name: ZMON_AGENT_KUBERNETES_CLUSTER_ID
              value: "{{ .ID }}"
            - name: ZMON_AGENT_KUBERNETES_CLUSTER_ALIAS
              value: "{{ .Alias }}"
            - name: ZMON_AGENT_KUBERNETES_CLUSTER_ENVIRONMENT
              value: "{{ .Environment }}"

            - name: ZMON_AGENT_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: zmon-worker
                  key: sql-user
            - name: ZMON_AGENT_POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: zmon-worker
                  key: sql-pass

            - name: OAUTH2_ACCESS_TOKEN_URL
              value: https://token.services.auth.zalando.com/oauth2/access_token?realm=/services
            - name: CREDENTIALS_DIR
              value: /meta/credentials
            - name: ZMON_HOSTED_ZONE_FORMAT_STRING
              value: "{}.{}.zalan.do"
          volumeMounts:
            - name: credentials
              mountPath: /meta/credentials
              readOnly: true

        - name: gerry
          image: registry.opensource.zalan.do/teapot/gerry:v0.0.14
          args:
            - /meta/credentials
            - --application-id=gerry
            - --mint-bucket=s3://{{ .ConfigItems.gerry_mint_bucket }}
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 10Mi

          volumeMounts:
            - name: credentials
              mountPath: /meta/credentials
              readOnly: false

      volumes:
        - name: credentials
          emptyDir:
            medium: Memory
