apiVersion: v1
kind: ServiceAccount
metadata:
  name: "deployment-service-controller"
  namespace: "kube-system"
  labels:
    application: "deployment-service"
    component: "controller"
  annotations:
    iam.amazonaws.com/role: "{{.Cluster.LocalID}}-deployment-service-controller"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "deployment-service-controller"
  labels:
    application: "deployment-service"
    component: "controller"
rules:
  - apiGroups:
      - deployment.zalando.org
    resources:
      - cdpdeploymenttasks
      - cdpdeploymenttasks/status
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - ""
      - "events.k8s.io"
    resources:
      - events
    verbs:
      - create
      - patch
      - update
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "deployment-service-controller"
  labels:
    application: "deployment-service"
    component: "controller"
subjects:
  - kind: ServiceAccount
    name: "deployment-service-controller"
    namespace: "kube-system"
roleRef:
  kind: ClusterRole
  name: "deployment-service-controller"
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "deployment-service-executor-poweruser"
  labels:
    application: "deployment-service"
    component: "controller"
roleRef:
  kind: ClusterRole
  name: poweruser
  apiGroup: rbac.authorization.k8s.io
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: zalando-iam:zalando:service:k8sapi-local_deployment-service-executor
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "deployment-service-executor-readonly"
  labels:
    application: "deployment-service"
    component: "controller"
roleRef:
  kind: ClusterRole
  name: readonly
  apiGroup: rbac.authorization.k8s.io
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: zalando-iam:zalando:service:k8sapi-local_deployment-service-executor
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "deployment-service-controller"
  namespace: "kube-system"
  labels:
    application: "deployment-service"
    component: "controller"
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
    resourceNames:
      - deployment-config
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "deployment-service-controller"
  namespace: "kube-system"
  labels:
    application: "deployment-service"
    component: "controller"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "deployment-service-controller"
subjects:
  - kind: ServiceAccount
    name: "deployment-service-controller"
    namespace: "kube-system"
