apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-node-ready-controller
  namespace: kube-system
  labels:
    application: kube-node-ready-controller
    version: v0.0.4
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: kube-node-ready-controller
  template:
    metadata:
      labels:
        application: kube-node-ready-controller
        version: v0.0.4
    spec:
      serviceAccountName: system
      tolerations:
      - key: zalando.org/node-not-ready
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: kube-node-ready-controller
        image: registry.opensource.zalan.do/teapot/kube-node-ready-controller:v0.0.4
        args:
        - --not-ready-taint-name=zalando.org/node-not-ready
        # only handle worker nodes
        - --node-selector=kubernetes.io/role=worker
        # format <namespace>:<labelKey>=<labelValue>,+
        - "--pod-selector=kube-system:application=kube2iam"
        - "--pod-selector=kube-system:application=kube-proxy"
{{ if eq .ConfigItems.logging_agent_enabled "true" }}
        - "--pod-selector=kube-system:application=logging-agent"
{{ end }}
        - "--pod-selector=kube-system:application=prometheus-node-exporter"
        - "--pod-selector=kube-system:application=flannel"
        - "--pod-selector=kube-system:application=kube-node-ready"
        - "--pod-selector=kube-system:application=dnsmasq-node"
        resources:
          limits:
            cpu: 20m
            memory: 50Mi
          requests:
            cpu: 20m
            memory: 50Mi
      nodeSelector:
        node-role.kubernetes.io/master: ""
