apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-updater
  namespace: kube-system
  labels:
    application: vertical-pod-autoscaler
    component: updater
    version: v0.6.1-internal.dev-98
spec:
  replicas: 1
  selector:
    matchLabels:
      application: vertical-pod-autoscaler
      component: updater
  template:
    metadata:
      labels:
        application: vertical-pod-autoscaler
        component: updater
        version: v0.6.1-internal.dev-98
      annotations:
        logging/destination: "{{.Cluster.ConfigItems.log_destination_infra}}"
    spec:
      serviceAccountName: vpa-updater
      containers:
      - name: updater
        image: registry.opensource.zalan.do/teapot/vpa-updater:v0.6.1-internal.dev-98
        command:
          - ./updater
        args:
          - --v=1
          - --logtostderr
          - --min-replicas=1
          - --pod-lifetime-update-threshold=12h
          - --evict-after-oom-threshold=12h
        resources:
          limits:
            cpu: {{.Cluster.ConfigItems.vpa_cpu}}
            memory: {{.Cluster.ConfigItems.vpa_mem}}
          requests:
            cpu: {{.Cluster.ConfigItems.vpa_cpu}}
            memory: {{.Cluster.ConfigItems.vpa_mem}}
        ports:
        - containerPort: 8080
          protocol: TCP
