apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-dns-b-autoscaler
  namespace: kube-system
  labels:
    application: kube-dns-b-autoscaler
    version: v1.1.2
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-dns-b-autoscaler
  template:
    metadata:
      labels:
        application: kube-dns-b-autoscaler
        version: v1.1.2
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: system
      containers:
      - name: autoscaler
        image: registry.opensource.zalan.do/teapot/cluster-proportional-autoscaler:1.1.2-r2
        resources:
          requests:
            cpu: "20m"
            memory: "10Mi"
        command:
          - /cluster-proportional-autoscaler
          - --namespace=kube-system
          - --configmap=kube-dns-b-autoscaler
          - --target=Deployment/kube-dns-b
          - --default-params={"linear":{"coresPerReplica":256,"nodesPerReplica":16,"preventSinglePointFailure":true}}
          - --logtostderr=true
          - --v=2
