apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-node-ready
  namespace: kube-system
{{ if eq .Cluster.ConfigItems.teapot_admission_controller_service_account_iam "true" }}
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Cluster.InfrastructureAccount | getAWSAccountID }}:role/{{ .Cluster.LocalID }}-kube-node-ready"
    iam.amazonaws.com/role: "{{ .Cluster.LocalID }}-kube-node-ready"
{{ end }}
