kind: Service
apiVersion: v1
metadata:
  name: kube-node-ready
  namespace: kube-system
  labels:
    application: kube-node-ready
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "kube-node-ready"
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30797
      targetPort: 8080
  selector:
    application: kube-node-ready
