apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-dns-metrics
  namespace: kube-system
  labels:
    application: kube-dns-metrics
    version: v1.0.2
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-dns-metrics
  template:
    metadata:
      labels:
        application: kube-dns-metrics
        version: v1.0.2
    spec:
      containers:
        - image: pierone.stups.zalan.do/teapot/kube-dns-metrics:v1.0.2
          name: kube-dns-metrics
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 25m
              memory: 25Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 3
          ports:
            - containerPort: 8080
            - containerPort: 9000
