apiVersion: apps/v1
kind: Deployment
metadata:
  name: zmon-scheduler
  namespace: visibility
  labels:
    application: zmon-scheduler
    version: "v43"
spec:
  replicas: 1
  selector:
    matchLabels:
      application: zmon-scheduler
  template:
    metadata:
      labels:
        application: zmon-scheduler
        version: "v43"
      annotations:
        iam.amazonaws.com/role: "{{ .LocalID }}-app-zmon"
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists

      initContainers:
      - name: gerry-init
        image: registry.opensource.zalan.do/teapot/gerry:v0.0.14
        args:
          - /meta/credentials
          - --application-id=gerry
          - --mint-bucket=s3://{{ .ConfigItems.gerry_mint_bucket }}
          - --once
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi

        volumeMounts:
          - name: credentials
            mountPath: /meta/credentials
            readOnly: false

      containers:
        - name: zmon-scheduler
          image: "registry.opensource.zalan.do/stups/zmon-scheduler:v43"
          resources:
            limits:
              cpu: 2
              memory: 1.5Gi
            requests:
              cpu: 100m
              memory: 512Mi

          ports:
            - containerPort: 7979
            - containerPort: 8085

          readinessProbe:
            httpGet:
              path: /health
              port: 7979
            initialDelaySeconds: 30
            periodSeconds: 60

          env:
            - name: LOCAL_ENTITY_ID
              value: kube-cluster[{{ .ID }}]

            - name: MEM_TOTAL_KB
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
                  divisor: 1Ki

            - name: SCHEDULER_OAUTH2_ACCESS_TOKEN_URL
              value: https://token.services.auth.zalando.com/oauth2/access_token?realm=/services
            - name: CREDENTIALS_DIR
              value: /meta/credentials
            - name: ZMON_BASE_URL
              value: https://data-service.zmon.zalan.do

            - name: MANAGEMENT_PORT
              value: "7979"

            - name: SCHEDULER_REDIS_HOST
              value: zmon-redis
            - name: SCHEDULER_REDIS_PORT
              value: "6379"

            - name: SCHEDULER_ENTITY_BASE_FILTER_STR
              value: '[{"infrastructure_account":"{{ .InfrastructureAccount }}","region":"{{ .Region }}"{{ if eq .Alias "db" }}, "kube_cluster":"{{ .ID }}"{{ end }}}]'
            - name: SCHEDULER_INSTANT_EVAL_HTTP_URL
              value: https://data-service.zmon.zalan.do/api/v1/instant-evaluations/kube-cluster[{{ .InfrastructureAccount }}:{{ .Region }}]/
            - name: SCHEDULER_TRIAL_RUN_HTTP_URL
              value: https://data-service.zmon.zalan.do/api/v1/trial-runs/kube-cluster[{{ .InfrastructureAccount }}:{{ .Region }}]/
            - name: SCHEDULER_DOWNTIME_HTTP_URL
              value: https://data-service.zmon.zalan.do/api/v1/downtimes/kube-cluster[{{ .InfrastructureAccount }}:{{ .Region }}]/
            - name: SCHEDULER_CHECK_DETAIL_METRICS
              value: "true"
            - name: SCHEDULER_ENTITY_SERVICE_URL
              value: https://data-service.zmon.zalan.do/
            - name: SCHEDULER_CONTROLLER_URL
              value: https://data-service.zmon.zalan.do/
            - name: SCHEDULER_ENABLE_GLOBAL_ENTITY
              value: "false"

          volumeMounts:
            - name: credentials
              mountPath: /meta/credentials
              readOnly: true

        - name: gerry
          image: registry.opensource.zalan.do/teapot/gerry:v0.0.14
          args:
            - /meta/credentials
            - --application-id=gerry
            - --mint-bucket=s3://{{ .ConfigItems.gerry_mint_bucket }}
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 10Mi

          volumeMounts:
            - name: credentials
              mountPath: /meta/credentials
              readOnly: false

      volumes:
        - name: credentials
          emptyDir:
            medium: Memory
