apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: zmon-scheduler
  namespace: visibility
  labels:
    application: zmon-scheduler
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zmon-scheduler
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: zmon-scheduler
      maxAllowed:
        cpu: 1000m
        memory: 2.5Gi
