{{ if eq .Cluster.ConfigItems.network_monitoring_enabled "true" }}
---
# Source: kubenurse/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubenurse
  labels:
    application: kubernetes
    component: kubenurse
  namespace: kubenurse
{{end}}