{{ if eq .Cluster.ConfigItems.network_monitoring_enabled "true" }}
  {{ if or (eq .Cluster.ConfigItems.network_monitoring_check_kubenurse_service "true") (eq .Cluster.ConfigItems.network_monitoring_check_kubenurse_ingress "true")}}
---
# Source: kubenurse/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    application: kubernetes
    component: kubenurse
  name: "kubenurse"
  namespace: kubenurse
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    application: kubernetes
    component: kubenurse
{{end}}
{{end}}