{{ if ne .Cluster.ConfigItems.audittrail_url "" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: audittrail-adapter
  namespace: kube-system
{{ if eq .Cluster.ConfigItems.teapot_admission_controller_service_account_iam "true" }}
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Cluster.InfrastructureAccount | getAWSAccountID }}:role/{{ .LocalID }}-audittrail-adapter"
    iam.amazonaws.com/role: "{{ .LocalID }}-audittrail-adapter"
{{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: audittrail-adapter-privileged-psp
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp
subjects:
- kind: ServiceAccount
  name: audittrail-adapter
  namespace: kube-system
{{ end }}
