apiVersion: apps/v1
kind: Deployment
metadata:
  name: "zmon-redis"
  namespace: "visibility"
  labels:
    application: "zmon-redis"
    version: "v0.1"
spec:
  replicas: {{.ConfigItems.zmon_redis_replicas}}
  selector:
    matchLabels:
      application: "zmon-redis"
  template:
    metadata:
      labels:
        application: "zmon-redis"
        version: "v0.1"
    spec:
      priorityClassName: visibility-zmon
      containers:
        - name: zmon-redis
          image: registry.opensource.zalan.do/zmon/redis:3.2.9
          resources:
            limits:
              cpu: 80m
              memory: {{.ConfigItems.zmon_redis_mem}}
            requests:
              cpu: 80m
              memory: {{.ConfigItems.zmon_redis_mem}}
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 60
