# everything defined under here will be deleted before applying the manifests
pre_apply:
- name: stackset-controller
  namespace: default
  kind: Service
- name: stackset-controller
  namespace: default
  kind: Deployment
- name: stackset-controller
  namespace: default
  kind: ServiceAccount
- name: kubernetes-dashboard-new
  namespace: kube-system
  kind: Deployment
- name: dashboard-metrics-scraper-new
  namespace: kube-system
  kind: Deployment
- name: cadvisor
  namespace: kube-system
  kind: DaemonSet
- name: prometheus-node-exporter
  namespace: kube-system
  kind: DaemonSet
{{ if ne .Cluster.ConfigItems.routegroups_validation "enabled" }}
- name: "routegroup-admitter.teapot.zalan.do"
  kind: ValidatingWebhookConfiguration
{{ end }}
{{ if eq .Cluster.Environment "e2e" }}
- name: pool-reserve-worker-spot-termination-handler
  namespace: default
  kind: Deployment
{{ end }}
# Application consolidation, can be dropped later
{{if eq .Cluster.Environment "e2e"}}
- labels:
    application: kube-aws-iam-controller
  namespace: kube-system
  kind: Deployment
- labels:
    application: kube-metrics-adapter
  namespace: kube-system
  kind: Deployment
{{ end }}

# everything defined under here will be deleted after applying the manifests
post_apply:
- name: stackset-controller
  namespace: default
  kind: VerticalPodAutoscaler
- name: spotinst-kubernetes-cluster-controller
  namespace: kube-system
  kind: VerticalPodAutoscaler
{{ if eq .ConfigItems.teapot_admission_controller_process_resources "true" }}
- name: limits
  namespace: default
  kind: LimitRange
- name: limits
  namespace: cron
  kind: LimitRange
{{ end }}
- name: leader-locking-efs-provisioner
  namespace: default
  kind: RoleBinding
{{ if ne .ConfigItems.enable_csi_migration "true" }}
- name: csi-node-driver
  namespace: kube-system
  kind: DaemonSet
- name: ebs-csi-controller
  namespace: kube-system
  kind: DaemonSet
- name: ebs
  kind: StorageClass
  namespace: kube-system
{{ end }}
{{ if ne .ConfigItems.prometheus_csi_ebs "true" }}
- name: prometheus-csi
  namespace: kube-system
  kind: StatefulSet
- name: prometheus-storage-volume-prometheus-csi-0
  kind: PersistentVolumeClaim
  namespace: kube-system
- name: prometheus-storage-volume-prometheus-csi-1
  kind: PersistentVolumeClaim
  namespace: kube-system
{{ else }}
- name: prometheus
  namespace: kube-system
  kind: StatefulSet
- name: prometheus-storage-volume-prometheus-0
  kind: PersistentVolumeClaim
  namespace: kube-system
- name: prometheus-storage-volume-prometheus-1
  kind: PersistentVolumeClaim
  namespace: kube-system
{{ end }}
# TODO: drop once rolled out to all clusters
- name: aws-node-decommissioner-aws-iam-credentials
  namespace: kube-system
  kind: AWSIAMRole
  apiVersion: zalando.org/v1
- name: kube-dns-metrics
  namespace: kube-system
  kind: Deployment
{{ if ne .ConfigItems.downscaler_enabled "true" }}
- name: kube-downscaler
  namespace: kube-system
  kind: Deployment
- name: kube-downscaler
  namespace: kube-system
  kind: ServiceAccount
- name: kube-downscaler
  kind: ClusterRole
- name: kube-downscaler
  kind: ClusterRoleBinding
- name: kube-downscaler
  namespace: kube-system
  kind: VerticalPodAutoscaler
{{ end }}
- name: patch-nodes
  namespace: kube-system
  kind: RoleBinding
- name: node-patcher
  kind: ClusterRole
- name: cadvisor
  namespace: kube-system
  kind: ServiceAccount
- name: cadvisor
  namespace: kube-system
  kind: Service
- name: cadvisor-privileged-psp
  namespace: kube-system
  kind: RoleBinding
- name: prometheus-node-exporter
  namespace: kube-system
  kind: ServiceAccount
- name: prometheus-node-exporter
  namespace: kube-system
  kind: Service
- name: prometheus-node-exporter-privileged-psp
  namespace: kube-system
  kind: RoleBinding
- name: visibility-logging
  kind: PriorityClass
- name: autoscaling-buffer
  kind: PriorityClass
- kind: ClusterRole
  name: default-psp
- kind: ClusterRoleBinding
  name: default-psp
- kind: PodSecurityPolicy
  name: default
- name: admission-controller-proxy
  kind: PlatformCredentialsSet
  namespace: kube-system
- name: admission-controller-proxy
  kind: DaemonSet
  namespace: kube-system
- name: ebs-csi-controller-iam-credentials
  namespace: kube-system
  kind: AWSIAMRole
  apiVersion: zalando.org/v1
- name: stackset-controller
  namespace: kube-system
  kind: Service
- name: kubernetes-lifecycle-metrics
  namespace: kube-system
  kind: Service
- name: kube-static-egress-controller
  namespace: kube-system
  kind: Service
- name: kube-node-ready-controller
  namespace: kube-system
  kind: Service
- name: kube-cluster-autoscaler
  namespace: kube-system
  kind: Service
- name: external-dns
  namespace: kube-system
  kind: Service
- name: audittrail-adapter
  namespace: kube-system
  kind: Service
- name: coredns-local-dnsmasq
  namespace: kube-system
  kind: Service
- labels:
    application: external-dns
  namespace: kube-system
  kind: Pod
{{- if ne .Cluster.ConfigItems.okta_auth_enabled "true" }}
- name: cluster-admin-okta
  kind: ClusterRoleBinding
{{- end }}
{{- if ne .Cluster.ConfigItems.deployment_service_enabled "true" }}
- kind: ClusterRole
  name: deployment-service-api-task-access
- kind: ClusterRoleBinding
  name: deployment-service-api-task-access
- kind: Role
  namespace: kube-system
  name: deployment-service-api-read-config
- kind: RoleBinding
  namespace: kube-system
  name: deployment-service-api-read-config
{{- end }}
