# example: remove the app-ingress-controller deployment from kube-system
# pre_apply:
# - name: app-ingress-controller
#   namespace: kube-system
#   kind: deployment

pre_apply: # everything defined under here will be deleted before applying the manifests
- name: emergency-access-service
  namespace: kube-system
  kind: deployment
- name: emergency-access-service
  namespace: kube-system
  kind: service
- name: emergency-access-service
  namespace: kube-system
  kind: ingress
- name: emergency-access-service-secrets
  namespace: kube-system
  kind: secret
post_apply: [] # everything defined under here will be deleted after applying the manifests
