# everything defined under here will be deleted before applying the manifests
pre_apply: []

# everything defined under here will be deleted after applying the manifests
post_apply:
- name: compute-resources
  namespace: default
  kind: ResourceQuota
- name: compute-resources
  namespace: kube-system
  kind: ResourceQuota
{{ if eq .ConfigItems.teapot_admission_controller_process_resources "true" }}
- name: limits
  namespace: default
  kind: LimitRange
{{ end }}
- name: kube-job-cleaner
  namespace: kube-system
  kind: CronJob
{{ if ne .ConfigItems.enable_ingress_template_controller "true" }}
- name: ingresstemplates.zalando.org
  kind: CustomResourceDefinition
- name: ingress-template-controller
  namespace: kube-system
  kind: Deployment
- name: ingress-template-controller
  namespace: kube-system
  kind: ServiceAccount
- name: ingress-template-controller
  kind: ClusterRole
- name: ingress-template-controller
  kind: ClusterRoleBinding
{{ end }}
- name: nvidia-driver-installer
  namespace: kube-system
  kind: DaemonSet
- name: admission-controller
  namespace: kube-system
  kind: ServiceAccount
- name: admission-controller
  kind: ClusterRole
- name: admission-controller
  kind: ClusterRoleBinding
- name: zmon-scheduler
  kind: VerticalPodAutoscaler
  namespace: visibility
- name: kubernetes-dashboard
  kind: RoleBinding
  namespace: kube-system
- name: system
  namespace: kube-system
  kind: ServiceAccount
- name: privileged-psp
  namespace: kube-system
  kind: RoleBinding
