# everything defined under here will be deleted before applying the manifests
pre_apply:
{{ if ne .Cluster.ConfigItems.routegroups_validation "enabled" }}
- name: "routegroup-admitter.teapot.zalan.do"
  kind: ValidatingWebhookConfiguration
{{ end }}
- name: cronjob-monitor
  namespace: kube-system
  kind: Deployment

# everything defined under here will be deleted after applying the manifests
post_apply:
- name: cronjob-monitor
  namespace: kube-system
  kind: VerticalPodAutoscaler
- name: cronjob-monitor
  kind: ClusterRole
- name: cronjob-monitor
  kind: ClusterRoleBinding
- name: cronjob-monitor
  namespace: kube-system
  kind: ServiceAccount
{{ if eq .ConfigItems.teapot_admission_controller_process_resources "true" }}
- name: limits
  namespace: default
  kind: LimitRange
- name: limits
  namespace: cron
  kind: LimitRange
{{ end }}
{{ if ne .ConfigItems.downscaler_enabled "true" }}
- name: kube-downscaler
  namespace: kube-system
  kind: Deployment
- name: kube-downscaler
  namespace: kube-system
  kind: ServiceAccount
- name: kube-downscaler
  kind: ClusterRole
- name: kube-downscaler
  kind: ClusterRoleBinding
- name: kube-downscaler
  namespace: kube-system
  kind: VerticalPodAutoscaler
{{ end }}
{{ if ne .ConfigItems.spot_node_rescheduler "true" }}
- name: node-spot-rescheduler
  namespace: kube-system
  kind: CronJob
- name: spot-node-rescheduler
  namespace: kube-system
  kind: CronJob
- name: spot-node-rescheduler
  namespace: kube-system
  kind: ServiceAccount
- name: spot-node-rescheduler
  kind: ClusterRole
- name: spot-node-rescheduler
  kind: ClusterRoleBinding
{{ end }}
{{- if ne .Cluster.ConfigItems.okta_auth_enabled "true" }}
- name: cluster-admin-okta
  kind: ClusterRoleBinding
{{- end }}

{{ if eq .Cluster.ConfigItems.skipper_routesrv_enabled "false" }}
- name: skipper-ingress-routesrv
  namespace: kube-system
  kind: Deployment
{{ end }}

{{- if ne .ConfigItems.skipper_oauth2_ui_login "true" }}
# hostname-credentials-controller
- kind: CronJob
  name: hostname-credentials-controller
  namespace: kube-system
- kind: ClusterRoleBinding
  name: hostname-credentials-controller
- kind: ClusterRole
  name: hostname-credentials-controller
- kind: ServiceAccount
  name: hostname-credentials-controller
  namespace: kube-system
- kind: PlatformCredentialsSet
  namespace: kube-system
  labels:
    application: skipper-ingress
    component: hostname-credentials

# secret-combiner
- kind: CronJob
  name: secret-combiner
  namespace: kube-system
- kind: RoleBinding
  name: secret-combiner
  namespace: kube-system
- kind: Role
  name: secret-combiner
  namespace: kube-system
- kind: ServiceAccount
  name: secret-combiner
  namespace: kube-system
- kind: Secret
  name: hostname-credentials
  namespace: kube-system
{{- end }}

{{- if eq .ConfigItems.prometheus_remote_write "disabled" }}
- name: prometheus-credentials
  kind: PlatformCredentialsSet
  namespace: kube-system
{{- end }}
{{- if eq .Cluster.ConfigItems.network_monitoring_check_unschedulable_nodes "true" }}
- kind: ClusterRole
  name: kubenurse
- kind: ClusterRoleBinding
  name: kubenurse
{{- end }}
{{- if eq .Cluster.ConfigItems.network_monitoring_separate_prometheus "false"}}
- kind: ClusterRole
  name: kubenurse-prometheus
- kind: ClusterRoleBinding
  name: kubenurse-prometheus
- kind: StatefulSet
  name: prometheus
  namespace: kubenurse
- kind: VerticalPodAutoscaler
  name: kubenurse-prometheus-vpa
  namespace: kubenurse
- kind: ConfigMap
  name: prometheus-conf
  namespace: kubenurse
- kind: ServiceAccount
  name: prometheus
  namespace: kubenurse
{{- end }}
{{- if eq .Cluster.ConfigItems.network_monitoring_enabled "false" }}
- kind: Namespace
  name: kubenurse
- kind: ClusterRole
  name: kubenurse
- kind: ClusterRoleBinding
  name: kubenurse
- kind: ClusterRole
  name: kubenurse-prometheus
- kind: ClusterRoleBinding
  name: kubenurse-prometheus
{{- end }}
