pre_apply: # everything defined under here will be deleted before applying the manifests
- name: app-ingress-controller
  namespace: kube-system
  kind: deployment
- name: secretary
  namespace: kube-system
  kind: deployment
- name: logging-agent
  namespace: kube-system
  kind: daemonset
