# example: remove the app-ingress-controller deployment from kube-system
# pre_apply:
# - name: app-ingress-controller
#   namespace: kube-system
#   kind: deployment

# everything defined under here will be deleted before applying the manifests
pre_apply:
- name: autoscaling-buffer
  namespace: kube-system
  kind: deployment

# everything defined under here will be deleted after applying the manifests
post_apply:
- name: kube-dns
  namespace: kube-system
  kind: service
- name: kube-dns
  namespace: kube-system
  kind: deployment
- name: kube-dns-autoscaler
  namespace: kube-system
  kind: deployment
