# example: remove the app-ingress-controller deployment from kube-system
# pre_apply:
# - name: app-ingress-controller
#   namespace: kube-system
#   kind: deployment

# everything defined under here will be deleted before applying the manifests
pre_apply:
- name: kube-cluster-autoscaler
  namespace: kube-system
  kind: deployment

# everything defined under here will be deleted after applying the manifests
post_apply: []
