# everything defined under here will be deleted before applying the manifests
pre_apply: []

# everything defined under here will be deleted after applying the manifests
post_apply:
- name: compute-resources
  namespace: default
  kind: ResourceQuota
- name: compute-resources
  namespace: kube-system
  kind: ResourceQuota
{{ if eq .ConfigItems.teapot_admission_controller_process_resources "true" }}
- name: limits
  namespace: default
  kind: LimitRange
{{ end }}
- name: kube-job-cleaner
  namespace: kube-system
  kind: CronJob
{{ if ne .ConfigItems.enable_ingress_template_controller "true" }}
- name: ingresstemplates.zalando.org
  kind: CustomResourceDefinition
{{ end }}
- name: nvidia-driver-installer
  namespace: kube-system
  kind: DaemonSet
