# everything defined under here will be deleted before applying the manifests
pre_apply:
- name: vpa-admission-controller-new
  namespace: kube-system
  kind: Deployment

# everything defined under here will be deleted after applying the manifests
post_apply:{{ if and (ne .ConfigItems.teapot_admission_controller_process_resources "true") (eq .ConfigItems.enable_ingress_template_controller "true") }} []{{ end }}
{{ if eq .ConfigItems.teapot_admission_controller_process_resources "true" }}
- name: limits
  namespace: default
  kind: LimitRange
- name: limits
  namespace: cron
  kind: LimitRange
{{ end }}
{{ if ne .ConfigItems.enable_ingress_template_controller "true" }}
- name: ingresstemplates.zalando.org
  kind: CustomResourceDefinition
- name: ingress-template-controller
  namespace: kube-system
  kind: Deployment
- name: ingress-template-controller
  namespace: kube-system
  kind: ServiceAccount
- name: ingress-template-controller
  kind: ClusterRole
- name: ingress-template-controller
  kind: ClusterRoleBinding
{{ end }}
- name: leader-locking-efs-provisioner
  namespace: default
  kind: Role
