kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: poweruser
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: poweruser
subjects:
- kind: Group
  name: PowerUser
  apiGroup: rbac.authorization.k8s.io
{{- if eq .Cluster.Environment "test" }}
- kind: Group
  name: CollaboratorPowerUser
  apiGroup: rbac.authorization.k8s.io
{{- end }}
- kind: Group
  name: Manual
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: Emergency
  apiGroup: rbac.authorization.k8s.io
{{- if eq .Cluster.ConfigItems.okta_auth_enabled "true" }}
- kind: Group
  name: "okta:common/engineer"
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: "okta:common/collaborator"
  apiGroup: rbac.authorization.k8s.io
{{- end }}
